# Lambda Function Comparison Configuration
# Define pairs of Lambda functions to compare

comparisons:
  - function1: rnd/myTestFunction1
    function2: prod/myTestFunction1
  
  - function1: rnd/myTestFunction2
    function2: prod/myTestFunction2
